# Generated by Django 5.1.7 on 2025-05-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='birth_year',
            field=models.IntegerField(null=True),
        ),
    ]
