# Generated by Django 5.1.7 on 2025-04-25 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilemarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pmodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobilemarket.pmodel', verbose_name='型號'),
        ),
    ]
